version: "3"

services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=express_example
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "3318:3306"